spring:
  application:
    name: graphvirtual

  graphql:
    graphiql:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/codefactory_db_virtual  # URL de la base de datos PostgreSQL
    driver-class-name: org.postgresql.Driver
    username: user_deploy                                  # Nombre de usuario para la base de datos
    password: p0stgr3s                                     # Contraseña de la base de datos
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update                                     # Configuración para crear/actualizar tablas automáticamente
    show-sql: true                                         # Mostrar consultas SQL en los logs

management:
  endpoint:
    health:
      show-details: always                                # Mostrar detalles de la salud del servicio
  endpoints:
    web:
      exposure:
        include: '*'                                      # Incluir todos los endpoints en la web

logging:
  level:
    org.springframework: DEBUG                            # Nivel de log para Spring Framework
    com.udea.vueloudea: DEBUG                             # Nivel de log para tu aplicación

server:
  port: 8014                                              # Puerto del servidor
  servlet:
    context-path: /modulo-14                              # Contexto de la aplicación
  ssl:
    enabled: false                                        # Desactivar SSL (si es necesario activarlo, ajusta la configuración SSL)
    key-store: classpath:codefact.p12                      # Archivo del key-store (solo si se usa SSL)
    key-store-password: 123456                             # Contraseña del key-store
    enabled-protocols: TLSv1.2                            # Protocolo de seguridad
    key-store-type: PKCS12                                 # Tipo de key-store
