apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    matchLabels:
      app: postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:13                    # Imagen de PostgreSQL, puedes cambiar la versión según sea necesario
          envFrom:
            - configMapRef:
                name: postgresql-config          # Nombre de la ConfigMap que contiene las variables de configuración
          ports:
            - containerPort: 5432                # Puerto de PostgreSQL
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
    - port: 5432                             # Puerto expuesto para PostgreSQL
      targetPort: 5432
  selector:
    app: postgresql
  type: ClusterIP
